# Generated by Django 3.0.3 on 2020-02-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
